#SPDX-License-Identifier: MIT-0
---
# tasks file for monitoring
# tasks file for monitoring

- name: Ensure kubeconfig for root
  file:
    path: /root/.kube
    state: directory
  tags: monitoring

- name: Copy kubeconfig to root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0600'
  tags: monitoring

- name: Install Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  tags: monitoring

- name: Add Helm repo
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
  environment:
    KUBECONFIG: /root/.kube/config
  tags: monitoring

- name: Create monitoring namespace
  shell: kubectl create namespace monitoring || true
  environment:
    KUBECONFIG: /root/.kube/config
  tags: monitoring

- name: Install kube-prometheus-stack
  shell: |
    helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
    --namespace monitoring
  environment:
    KUBECONFIG: /root/.kube/config
  tags: monitoring



